"""empty message

Revision ID: 48d9bad39caa
Revises: db9e43ee7335
Create Date: 2023-08-31 23:44:06.252772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d9bad39caa'
down_revision = 'db9e43ee7335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('house_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'house', ['house_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('house_id')

    op.drop_table('house')
    # ### end Alembic commands ###
